name: Release

on:
  pull_request:
    branches:
      - main

jobs:
  release:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 16-nightly
          check-latest: false
          cache: "pnpm"
      - name: Install Dependencies
        run: npm install -g pnpm
      - run: pnpm ci
      - run: pnpm run lint
      - name: Debug PATH
        run: echo $PATH

      - name: Get Release Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v3
        with:
          application_id: ${{ secrets.RELEASE_APP_ID  }}
          application_private_key: ${{ secrets.RELEASE_APP_CERT}}
      - run: pnpm dlx semantic-release
        env:
          GITHUB_TOKEN: ${{ steps.get_workflow_token.outputs.token }}
